# -*- coding: utf-8 -*-
"""Part_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ICaPGQ1WZ31-0-yspWlXcjhpQE4fUasJ
"""

from datetime import datetime
from psychopy import core, gui
from psychopy import visual, event
from psychopy.hardware import keyboard
import random
import os
import csv
import numpy as np


#Participants dialog box

date = datetime.now().strftime('%Y%m%d_%H%M')

dlg = gui.Dlg(title='Experiment')
dlg.addFixedField('expname', label='Experiment Name', initial = 'My test experiment')
dlg.addFixedField('expdate', label='Date', initial=date)

dlg.addField('Participant ID')
data = dlg.show()

if not dlg.OK:
    print("You cancelled the experiment")
    core.quit()

print(data)

filename = f"Par_{data['Participant ID']}_{data['expdate']}.csv"
print(filename)

#Saving CSV file
path_csv = os.path.join(os.getcwd(), filename)
response_file = open(path_csv, 'w')

response_file.write('Condition,Target,Word1,Word2,Word3,Answer,CorrectAnswer,RT,IsCorrect,Time\n')


#Reading stimuli file
with open('sampledata/trials.csv', 'r') as f:
    header = f.readline().strip().split(',')
    data = [line.strip().split(',') for line in f.readlines()]


#Group files by condition
#Create a dictionary where each key is a condition, and the corresponding value is a list of 10 trials.
conditions = ['colour', 'high', 'low', 'shape', 'size', 'texture']

con_dict = {}
for con in conditions:
    con_dict[con] = []

for trial in data:
    cond = trial[0].strip().lower()
    if cond in con_dict:
        con_dict[cond].append(trial)


#Setting window and key
win = visual.Window([1024, 768], fullscr=True, allowGUI=True, units="pix", color=(0,0,0))
kb = keyboard.Keyboard()


#Setting block
#Randomize 10 trials by each condition
blocks = []

for cond in con_dict:
    random.shuffle(con_dict[cond])
    blocks.append({'condition':cond,
                   'trials': con_dict[cond]})

random.shuffle(blocks)


#Set the position for each word on the screen
target = visual.TextStim(win, pos=(0, 150), height=60)
condition = visual.TextStim(win, pos=(0, 50), height=40)
word1 = visual.TextStim(win, pos=(-300, -150), height=60)
word2 = visual.TextStim(win, pos=(0, -150), height=60)
word3 = visual.TextStim(win, pos=(300, -150), height=60)


#Setting introduction message
intro_line = visual.TextStim(win, "Welcome to our experiment.\n\n"
                        "You will see a target word and three choices.\n\n"
                        "Choose the word closest to the meaning or to a specific feature of the target word as fast as possible.\n\n "
                        "Left Answer: Keypress '1'. Middle Answer: Keypress '2'. Right Answer: Keypress '3'\n\n"
                        "Press 'space' to start or 'escape' at any time to quit.", pos=(0, 0), color=(1,1,1), height=40, wrapWidth=2000)

intro_line.draw()
win.flip()


#Set up keys that the participant can press
#terminate the program when the Escape key is pressed.
keys = event.waitKeys(keyList=['space', 'escape'])

if 'escape' in keys:
    win.close()
    core.quit()


#Showing the fixation cross
if 'space' in keys:
    cross_stim = visual.TextStim(win, '+', height=100)
    cross_stim.draw()
    win.flip()
    core.wait(5.0)


#Show experiment blocks
for i, block in enumerate(blocks):
    block_condi = block['condition']

    #Present an example or cue of the stimulus to consider before the first block only
    if i == 0:
        intro_block = visual.TextStim(win, f"The experiment is about to begin.\n\n"
                                   f"In the next block choose the word that has a similar {block_condi}.\n\n"
                                   "Get READY!", pos=(0, 0), color=(1,1,1), height=40, wrapWidth = 2000)

    intro_block.draw()
    win.flip()
    core.wait(5.0)

    #Set the index for each trial according to its corresponding variables
    for trial in block['trials']:
        cross_stim.draw()
        win.flip()
        core.wait(1.0)

        condition.text = trial[0]
        target.text = trial[1]
        word1.text = trial[2]
        word2.text = trial[3]
        word3.text = trial[4]

        for stim in [target, condition, word1, word2, word3]:
            stim.draw()
        win.flip()
        core.wait(1.5)

        #Recording responses
        kb.clock.reset()
        keys = kb.waitKeys(maxWait=10, keyList=['1', '2', '3', 'escape'])
        if keys:
            key = keys[0].name
            rt = keys[0].rt
            if key == 'escape':
                win.close()
                core.quit()

            #Mark 1 for correct responses and 0 for incorrect ones
            is_correct = 1 if key == trial[5] else 0
        else:
            key = ''
            rt = 'NA'

        response_file.write(f"{condition.text},{target.text},{word1.text},{word2.text},{word3.text},{key},{trial[5]},{rt},{is_correct},{date}\n")


        cross_stim.draw()
        win.flip()
        core.wait(np.random.uniform(0.5, 2.5))


    #First Break Message
    #If it's not the last block, display a break message
    if i < len(blocks) - 1:
        next_condi = blocks[i+1]['condition']
        br_time = np.random.uniform(7.5, 12)
        half_br_time = br_time/2
        break_msg = visual.TextStim(win, "Take a short break, but please pay attention to the screen.\n\n"
                            "The experiment is going to start agian in a few seconds.", pos=(0, 0), color=(1,1,1), height=40, wrapWidth=2000)

        break_msg.draw()
        win.flip()
        core.wait(half_br_time)


    #Second Break Message
    #If it's not the first block, continuously display the second message
        if i != 0:
            restart_msg = visual.TextStim(win, f"The experiment is about to begin.\n"
                                   f"In the next block choose the word that has a similar {next_condi}.\n"
                                   "Get READY!", pos=(0, 0), color=(1,1,1), height=40, wrapWidth=2000)


            restart_msg.draw()
            win.flip()
            core.wait(half_br_time)


#Finish Experiment

fns_msg = visual.TextStim(win, "Congratulation! The experiment finished!\n\n" "Thank you for your attention!\n\n" "Have a good day! BYE!", pos=(0, 0), color=(1,1,1), height=40, wrapWidth=2000)

fns_msg.draw()
win.flip()
core.wait(4.0)

win.close()
core.quit()

